// Toggle mobile menu
    document.getElementById('menu-toggle').addEventListener('click', function() {
      document.getElementById('sidebar').classList.toggle('active');
    });

    // Add question functionality
    document.getElementById('add-question-btn').addEventListener('click', function() {
      const questionsList = document.querySelector('.questions-list');
      const questionCount = questionsList.children.length + 1;
      
      const newQuestion = document.createElement('div');
      newQuestion.className = 'question-item';
      newQuestion.innerHTML = `
        <div class="question-title">
          <h3>QUESTION ${questionCount}</h3>
          <button class="delete-question" style="margin-left: auto; background: #ff6b6b; color: white; border: none; border-radius: 4px; width: 25px; height: 25px; display: flex; align-items: center; justify-content: center; cursor: pointer;">
            <i class="fas fa-times"></i>
          </button>
        </div>
        <div class="question-content">
          <textarea placeholder="Enter question content"></textarea>
        </div>
      `;
      
      // Add delete functionality to the new button
      newQuestion.querySelector('.delete-question').addEventListener('click', function() {
        newQuestion.remove();
        // Renumber remaining questions
        const questions = document.querySelectorAll('.question-title h3');
        questions.forEach((question, index) => {
          question.textContent = `QUESTION ${index + 1}`;
        });
      });
      
      questionsList.appendChild(newQuestion);
    });

    // Save test functionality
    document.getElementById('save-test-btn').addEventListener('click', function() {
      const testName = document.getElementById('test-name').value;
      const testDescription = document.getElementById('test-description').value;
      
      if (!testName) {
        alert('Please enter a test name');
        return;
      }
      
      // Simulate saving
      this.textContent = 'SAVING...';
      this.disabled = true;
      
      setTimeout(() => {
        this.textContent = 'SAVED!';
        this.style.background = '#2e7d32';
        
        setTimeout(() => {
          this.textContent = 'SAVE TEST';
          this.disabled = false;
          this.style.background = '#8e44ad';
        }, 2000);
      }, 1500);
    });

    // AI Test Generation Modal functionality
    const aiTestModal = document.getElementById('ai-test-modal');
    const aiTestBtn = document.getElementById('ai-test-btn');
    const closeModalBtn = document.getElementById('close-modal');
    const generateTestBtn = document.getElementById('generate-test-btn');

    // Open modal
    aiTestBtn.addEventListener('click', function() {
      aiTestModal.classList.add('active');
    });

    // Close modal
    closeModalBtn.addEventListener('click', function() {
      aiTestModal.classList.remove('active');
    });

    // Close modal when clicking outside
    aiTestModal.addEventListener('click', function(e) {
      if (e.target === aiTestModal) {
        aiTestModal.classList.remove('active');
      }
    });

    // Generate test functionality
    generateTestBtn.addEventListener('click', function() {
      this.innerHTML = '<i class="fas fa-spinner fa-spin"></i> GENERATING...';
      this.disabled = true;
      
      setTimeout(() => {
        // Get selected options
        const difficulty = document.querySelector('input[name="difficulty"]:checked').value;
        const questionTypes = Array.from(document.querySelectorAll('input[name="question-types"]:checked'))
          .map(input => input.value);
        const questionCount = document.getElementById('question-count').value;
        
        // Apply to the main form
        document.getElementById('test-name').value = `AI Generated ${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)} Test`;
        document.getElementById('test-description').value = `This test was automatically generated by our AI system with ${questionCount} ${difficulty}-level questions including ${questionTypes.join(', ')} type questions.`;
        
        // Clear existing questions
        const questionsList = document.querySelector('.questions-list');
        questionsList.innerHTML = '';
        
        // Add AI generated questions
        for (let i = 1; i <= questionCount; i++) {
          const newQuestion = document.createElement('div');
          newQuestion.className = 'question-item';
          newQuestion.innerHTML = `
            <div class="question-title">
              <h3>QUESTION ${i}</h3>
            </div>
            <div class="question-content">
              <textarea placeholder="Enter question content">This is an AI-generated ${difficulty} difficulty question.</textarea>
            </div>
          `;
          questionsList.appendChild(newQuestion);
        }
        
        // Close modal and reset button
        aiTestModal.classList.remove('active');
        this.innerHTML = 'GENERATE TEST';
        this.disabled = false;
        
        alert('Test successfully generated with AI!');
      }, 2000);
    });

    // Test item selection
    const testItems = document.querySelectorAll('.test-item');
    testItems.forEach(item => {
      item.addEventListener('click', function() {
        testItems.forEach(i => i.classList.remove('active'));
        this.classList.add('active');
      });
    });